### ISSUE TITLE
リポジトリ名が抽象的

### ISSUE THREAD

**Issue by tacky0612** [im-miro/server-cheat-sheet#3]
タイトルの通りです。
cheatというリポジトリ名が抽象的で、他にチートシート的なのを立てるってなったときに混乱してしまう可能性があります。

README.mdにあるようにserver-cheat-sheetとかの方がcontributorがForkしたときに扱いやすいのでは？

（issue立ての練習）

**Comment by im-miro** [comment]
確かに抽象的だとフォークした後のクローンでもローカルでコンフリクトしてしまうこともありそうなので変更しておきます。ありがとうございます！！
